aws-vpc-cni:
  env:
    ENABLE_PREFIX_DELEGATION: "false"
    DISABLE_TCP_EARLY_DEMUX: "false"
    ENABLE_IPv4: "true"
    ENABLE_IPv6: "false"

  # this flag enables you to use the match label that was present in the original daemonset deployed by EKS
  # You can then annotate and label the original aws-node resources and 'adopt' them into a helm release
  originalMatchLabels: true

  crd:
    create: true

  eniConfig:
    create: false
    region: eu-west-1
