{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload.fullname" . }}
  labels: {{ include "workload.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
      protocol: {{ $value.protocol | default "TCP"}}
  {{- end }}
  selector: {{ include "workload.selectorLabels" . | nindent 4 }}
{{- end }}
