minio-operator:
  operator:
    image:
      repository: minio/operator
      tag: v4.2.14
      pullPolicy: IfNotPresent
    replicaCount: 1
    nodeSelector:
      workload: system
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 500Mi

  console:
    image:
      repository: minio/console
      tag: v0.10.0
      pullPolicy: IfNotPresent
    replicaCount: 1
    nodeSelector:
      workload: system
    resources: {}

  ## MinIO Tenant Definition
  tenants:
    - name: argo-workflows-artifacts
      image:
        repository: minio/minio
        tag: RELEASE.2021-10-06T23-36-31Z
        pullPolicy: IfNotPresent
      namespace: argo-workflows
      ## Specification for MinIO Pool(s) in this Tenant.
      pools:
        - servers: 1
          volumesPerServer: 4
          size: 10Gi
          ## storageClass specifies the storage class name to be used for this pool
          storageClassName: gp2
          nodeSelector:
            workload: system
          resources: {}
      ## Mount path where PV will be mounted inside container(s).
      mountPath: /export
      ## Sub path inside Mount path where MinIO stores data.
      subPath: /data
      # pool secrets
      secrets:
        # create a kubernetes secret object with the accessKey and secretKey as defined here.
        enabled: true
        name: argo-workflows-artifacts-secret
        accessKey: minio
        secretKey: minio123
      certificate:
        requestAutoCert: true
      ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
      ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
      s3:
        ## This feature is turned off by default
        bucketDNS: true

