apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-addons
  source:
    repoURL: git@gitlab.com:tikalk.com/fuse/hackathon-2022/group07/group07.git
    path: argocd/releases/prometheus/kube-prometheus-stack
    targetRevision: main
    helm:
      skipCrds: true
  destination:
    namespace: kube-prometheus-stack
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Prune=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 15m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-addons
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-41.7.0
    directory:
      recurse: true
  destination:
    namespace: kube-prometheus-stack
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Prune=true
      - Replace=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 15m
