apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - git:
        repoURL: git@gitlab.com:tikalk.com/fuse/hackathon-2022/group07/group07.git
        revision: main
        directories:
          - path: argocd/releases/system-components/*
  template:
    metadata:
      name: '{{ path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: system
      source:
        repoURL: git@gitlab.com:tikalk.com/fuse/hackathon-2022/group07/group07.git
        targetRevision: main
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: kube-system
      syncPolicy:
        syncOptions:
          - Force=true
          - Prune=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
        automated:
          selfHeal: true
          prune: true
        retry:
          limit: 10
          backoff:
            maxDuration: 15m
            factor: 2
            duration: 5s
