{{/*apiVersion: cert-manager.io/v1*/}}
{{/*kind: ClusterIssuer*/}}
{{/*metadata:*/}}
{{/*  name: letsencrypt-staging*/}}
{{/*  annotations:*/}}
{{/*    argocd.argoproj.io/sync-wave: "100"*/}}
{{/*spec:*/}}
{{/*  acme:*/}}
{{/*    email: alex.zeleznikov@tikalk.com*/}}
{{/*    server: https://acme-staging-v02.api.letsencrypt.org/directory*/}}
{{/*    privateKeySecretRef:*/}}
{{/*      name: letsencrypt-staging*/}}
{{/*    # Add a single challenge solver, HTTP01 using nginx*/}}
{{/*    solvers:*/}}
{{/*      - dns01:*/}}
{{/*          route53:*/}}
{{/*            region: eu-west-1*/}}
{{/*---*/}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: alex.zeleznikov@tikalk.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - dns01:
          route53:
            region: eu-west-1
