aws-efs-csi-driver:
  image:
    repository: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/aws-efs-csi-driver
    tag: v1.4.2

  controller:
    create: false
    tags: {}
    nodeSelector:
      workload: system

  node:
    tolerations:
      - operator: Exists

  storageClasses: []
  # Add StorageClass resources like:
  # - name: efs-sc
  #   annotations:
  #     # Use that annotation if you want this to your default storageclass
  #     storageclass.kubernetes.io/is-default-class: "true"
  #   mountOptions:
  #   - tls
  #   parameters:
  #     provisioningMode: efs-ap
  #     fileSystemId: fs-1122aabb
  #     directoryPerms: "700"
  #     gidRangeStart: "1000"
  #     gidRangeEnd: "2000"
  #     basePath: "/dynamic_provisioning"
  #   reclaimPolicy: Delete
  #   volumeBindingMode: Immediate

