apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-scheduler.fullname" . }}
  labels: {{ include "kube-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-scheduler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-scheduler.fullname" . }}-as-kube-scheduler
  labels: {{ include "kube-scheduler.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-scheduler.fullname" . }}-as-volume-scheduler
  labels: {{ include "kube-scheduler.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}
