apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-scheduler.fullname" . }}
  labels: {{ include "kube-scheduler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ include "kube-scheduler.fullname" . }}
    verbs:
      - create
      - list
      - watch
      - get
