kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kube-scheduler.fullname" . }}
  labels: {{ include "kube-scheduler.labels" . | nindent 4 }}
data:
  policy.cfg: |
    {
      "kind": "Policy",
      "apiVersion": "v1",
      "priorities": {{ toJson .Values.policyConfig }}
    }