apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-scheduler.fullname" . }}
  labels: {{ include "kube-scheduler.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
